### PR TITLE
remove .DS_Store

### PR DESCRIPTION
**Pull request by fowler446**
Typically work isn't done on the "master" branch but instead people create branches and merge them into master through pull requests.

### CODE REVIEW

**Comment by fowler446** [comment]
You can see that a .gitignore file consists of the names of the files you want to ignore each on a new line.

**Comment by shocktech** [comment]
I'll need this one explained; i believe.

**Comment by shocktech** [comment]
Do you think this is because I use the "git add -A" command ?

**Comment by fowler446** [comment]
Yeah ```git add -A``` will add all files to be tracked by git. Typically every project has a .gitignore so that you can use ```git add -A``` and not track files you don't want to track

**Pull request merged**
